server:
  port: 8891
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri:
eureka:
  instance:
    instance-id: service-config
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka