---
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
spring:
  profiles: server1
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
      roles: USER
---
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
spring:
  profiles: server2
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
      roles: USER